[package]
name = "one-click-kb-switch"
version = "0.1.0"
edition = "2024"
authors = ["Mykola"]
license = "MIT"
description = "Native-first keyboard layout switcher"
homepage = "https://github.com/Develastic/1-click-kb-switch"
repository = "https://github.com/Develastic/1-click-kb-switch"

[dependencies]
once_cell = "1"
anyhow = "1"
directories = "6"
font8x8 = "0.3"
global-hotkey = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tao = "0.34.6"
thiserror = "2"
tray-icon = { version = "0.21.3", default-features = false }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.2", features = [
  "Win32_Foundation",
  "Win32_Globalization",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_LibraryLoader",
  "Win32_System_Threading",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_WindowsAndMessaging",
] }

[dev-dependencies]
tempfile = "3"

[target.'cfg(target_os = "windows")'.build-dependencies]
winres = "0.1"

[package.metadata.wix]
upgrade-guid = "1D7CE10C-6FF1-4FE2-9B86-A166803E18AB"
path-guid = "D0F93A62-7E26-431D-BE54-5D9DB7194A15"
license = false
product-icon = "assets/app.ico"
eula = false
